### ISSUE TITLE
Should we use `Nullable` for optional arguments?

### ISSUE THREAD

**Issue by bicycle1885** [docopt/DocOpt.jl#11]
The current implementation returns `nothing` for optional arguments if they are not provided by users. Julia v0.4 started to support the `Nulalble` type, which enables to indicate a value is null or not. This type seems to be a reasonable way to return an optional argument, but breaks the backward compatibility.
In the next release, I'd like to provide optional values as nullable because it will be a standard way in the Julia community in the long run.

**Comment by staticfloat** [comment]
Turns out; returning `nothing` is the canonical "Nullable" now.  Way to see into the future, Kenta!
