### ISSUE TITLE
Not precompiling?

### ISSUE THREAD

**Issue by jeff-regier** [docopt/DocOpt.jl#13]
My first call to `docopt` takes about 4000 times longer than my second call to it. (4 seconds vs 0.001 second.) What's happening? Is Julia compiling the function during the first call, rather than pre-compiling the library? (I'm using both Julia 0.4 and Julia 0.5.)

```
julia> using DocOpt

julia> DOC = "Usage: my_program"
"Usage: my_program"

julia> @time     args = docopt(DOC)
  4.113140 seconds (1.88 M allocations: 80.758 MB, 12.67% gc time)
Dict{AbstractString,Any} with 0 entries

julia> @time     args = docopt(DOC)
  0.001893 seconds (400 allocations: 18.016 KB)
Dict{AbstractString,Any} with 0 entries

julia> isdefined(Base, :__precompile__)
true
```

**Comment by jeff-regier** [comment]
I ran it though the profiler. Looks like almost all the time is spent in `inference.jl`. I believe this means it's compiling the code when its first run, and that DocOpt isn't being precompiled. I'm not sure why that would be.

```
   803 ./inference.jl                               1583 typeinf_loop(::Core.Inference.InferenceState)    
   812 ./inference.jl                               1528 typeinf_edge(::Method, ::Any, ::SimpleVector,... 
   813 ./inference.jl                                846 abstract_call_gf_by_type(::Any, ::Any, ::Core... 
   869 ./inference.jl                               1037 abstract_call(::Any, ::Tuple{}, ::Array{Any,1... 
   921 ./inference.jl                               1067 abstract_eval_call(::Expr, ::Array{Any,1}, ::... 
  1183 ./inference.jl                               1088 abstract_eval(::Any, ::Array{Any,1}, ::Core.I... 
  1286 ./inference.jl                               1523 typeinf_edge(::Method, ::Any, ::SimpleVector,... 
```

**Comment by jeff-regier** [comment]
@tkelman suggests using [SnoopCompile.jl](https://github.com/timholy/SnoopCompile.jl) to pre-compile the `docopt` function and the functions it calls.

**Comment by bicycle1885** [comment]
I'm sorry for the delayed reply. I will take a look next week.

**Comment by mweastwood** [comment]
I have experimented a little with this. Unfortunately I have bad news.

It seems the majority of the overhead from the first run of `docopt` comes from compiling a bunch of Base functions. The contribution from compiling functions in the DocOpt package itself is largely negligible (you might get a few tenths of a second by doing the precompilation). Therefore you really need to compile Julia with a userimg if you want the first call of `docopt` to execute quickly (I've gotten it down to ~0.3 seconds from ~2 seconds).

The routine is fairly straight forward if you follow the steps in the SnoopCompile README.

**Comment by jeff-regier** [comment]
Good to know, thanks for looking into it!
