### ISSUE TITLE
Incorrect parsing symbols [ and ] which are mark optional part of argument.

### ISSUE THREAD

**Issue by denius** [docopt/DocOpt.jl#20]
If there is `[` and `]` in arguments then `DocOpt.jl` insert extra spaces around it.
```julia
using DocOpt
const doc = """Usage:
  test.jl <filename.dat[.gz]>
"""
arguments = docopt(doc)
println(arguments)
```
and running it with `julia test.jl 1.dat` yields
```julia
Dict{AbstractString,Any}(Pair{AbstractString,Any}("<filename.dat [ .gz ] >","1.dat"))
```

**Comment by staticfloat** [comment]
I don't think this is doing what you want it to be doing; I tried to reproduce this using the python docopt implementation, and it doesn't do what you want it to.  If you still care about this, please open a new issue showing how another implementation accepts something that this implementation doesn't, and we'll track down the bug.
