### ISSUE TITLE
return dict should be of type Dict{String,Any}

### ISSUE THREAD

**Issue by ggggggggg** [docopt/DocOpt.jl#21]
The dict returned by `docopt` is of type Dict{AbstractString,Any}. I think it should be of type Dict{String,Any}, as there is no chance of accidentially putting in a type other than String.

Changing [this line](https://github.com/docopt/DocOpt.jl/blob/master/src/DocOpt.jl#L604) seems to be sufficient, and passes tests on my computer.

**Comment by staticfloat** [comment]
This looks to be resolved.
