### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by kmsquire** [docopt/DocOpt.jl#9]
The current tagged version does not contain the `startswith` change from a few months ago.  

(It's not necessary for v0.3, but it will still work since you're using Compat, and v0.4 should (finally) be released soon.)

**Comment by bicycle1885** [comment]
I agree. But before releasing a new version, I'd like to clean up the code. I'l do it within a few weeks.

**Comment by kmsquire** [comment]
Ok

**Comment by bicycle1885** [comment]
v0.0.3 has been released.
